name: astr596
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.10
  
  # Core scientific packages
  - numpy>=1.24
  - scipy>=1.10
  - matplotlib>=3.7
  - pandas>=2.0
  - seaborn>=0.12
  - sympy>=1.12
  
  # Astronomy packages
  - astropy>=5.3
  - healpy>=1.16
  
  # Jupyter ecosystem
  - jupyterlab>=4.0
  - jupyter_server>=2.6
  - ipywidgets>=8.0
  - ipykernel>=6.25
  
  # Additional scientific packages
  - h5py>=3.9
  - scikit-learn>=1.3
  - tqdm
  
  # Development tools
  - ipython>=8.14
  - black>=23.0
  - pytest>=7.4
  
  # Pip packages not available in conda
  - pip
  - pip:
    # Optional heavy dependencies (JAX stack) - commented out to avoid CI/binder failures
    # - jax>=0.4.20
    # - jaxlib>=0.4.20
    # - optax>=0.1.7
    # - flax>=0.7.0

    # Plotting
    - plotly>=5.14.0

    # Format conversion
    - jupytext>=1.15.0

    # Notebook conversion and MyST tooling
    - nbformat>=5.9.0
    - nbconvert>=7.8.0
    - myst-nb>=0.16.0
    - myst-parser>=0.18.0
    - nbclient>=0.8.0